repos:
# Official repo for the clang-format hook
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v8.0.1'
  hooks:
  - id: clang-format
# Rust formatting hook
- repo: https://github.com/doublify/pre-commit-rust
  rev: 'v1.0'
  hooks:
    - id: fmt
# Official repo for default hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-xml
  - id: check-merge-conflict
  - id: mixed-line-ending
# Custom repo for the preCICE configuration formatter
- repo: https://github.com/precice/precice-pre-commit-hooks
  rev: 'v2.1'
  hooks:
  - id: format-precice-config
