repos:
# Official repo for the clang-format hook
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v22.1.2'
  hooks:
  - id: clang-format
# Rust formatting hook
- repo: https://github.com/doublify/pre-commit-rust
  rev: 'v1.0'
  hooks:
    - id: fmt
# Official repo for default hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: check-xml
  - id: check-merge-conflict
  - id: mixed-line-ending
# Custom repo for the preCICE configuration formatter
- repo: https://github.com/precice/config-format
  rev: 'v2.0.0'
  hooks:
  - id: precice-config-format
