[package]
name = "precice"
version = "2.5.0"
edition = "2021"
publish = false
description = "Rust bindinds for precice"
license = "LGPLv3"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
pkg-config = "0.3"
semver = "1"
clap = "2.9"

[[example]]
name = "solverdummy"
