name: Build and Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:

  workflow_dispatch:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build:
    name: ${{ format('{0} {1}', matrix.IMAGE, matrix.TYPE) }}
    runs-on: ubuntu-latest
    container: 'precice/${{ matrix.IMAGE }}'
    defaults:
      run:
        shell: "bash --login -eo pipefail {0}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE: 'precice:nightly'
            TYPE: Debug
          - IMAGE: 'precice:nightly'
            TYPE: Release
            CARGOFLAG: --release
    steps:
      - name: preCICE Version
        run: precice-tools version
      - name: Update APT
        run: apt-get -yy update && apt-get -yy upgrade
      - name: Install Cargo
        run: apt-get -yy install cargo
      - uses: actions/checkout@v4
      - name: Build bindings
        run: cargo build $CARGOFLAG 
      - name: Build solverdummy
        run: cargo build $CARGOFLAG --example=solverdummy
      - name: Run solverdummies
        run: |
          cargo run $CARGOFLAG --example=solverdummy -- examples/precice-config.xml SolverOne &
          cargo run $CARGOFLAG --example=solverdummy -- examples/precice-config.xml SolverTwo
