name: Code Style
on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install cargo
        run: |
          sudo apt-get -yy update
          sudo apt-get -yy install cargo
      - name: Run checks
        run: pre-commit run -a -v
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff
